/**
 * API layer — Phase 2A.
 */

export { ApiClient } from './client';
export type { AuthHeaders, ClientOptions } from './client';
export { useApi } from './useApi';
export {
  ApiError,
  isApiError,
  type OutputFormat,
  type ReportRequest,
  type ReportResponse,
  type ApproveRequest,
  type RejectRequest,
  type RequestRevisionRequest,
  type ApiHealthResponse,
  type ReportState,
  type ReportSummary,
  type ReportListResponse,
  type ReviewDecisionView,
  type ReportDetail,
  type ReportStatusResponse,
  type CancelReportResponse,
  type UploadResponse,
  type WorkspaceProject,
  type WorkspaceContextResponse,
  type EvidencePanelEntry,
  type ReportContentResponse,
  type ListReportsParams,
  type ConnectorCategory,
  type ConnectorAuthMechanism,
  type ConnectorProbeStatus,
  type ConnectorLastProbeStatus,
  type ConnectorEventType,
  type WorkflowStatus,
  type EnvKeyStatus,
  type ConnectorEventView,
  type ServiceSummary,
  type ServiceDetail,
  type ProbeResult,
  type HealthServiceStatus,
  type HealthLiveResponse,
  type LlmBreakdownItem,
  type CostResponse,
  type AuditEventSummary,
  type AuditEventDetail,
  type AuditEventListResponse,
  type ListAuditEventsParams,
  type EntraGroupMapping,
  type EntraGroupMappingUpsertRequest,
  type EntraGroupMappingListResponse,
  type SourceMappingSharePoint,
  type SourceMappingOwnCloud,
  type SourceMappingEmail,
  type SourceMappingOdoo,
  type RelatedPeople,
  type SourceMappingSummary,
  type SourceMappingDetail,
  type SourceMappingListResponse,
  type SourceMappingUpsertRequest,
  type ValidationFieldError,
  type SourceMappingValidateResponse,
} from './types';
