"""Runtime validation: report generation routes through DeepSeek, not the fallback.

Starts a local HTTP server that emulates the DeepSeek ``/chat/completions``
endpoint, points ``DEEPSEEK_BASE_URL`` at it, and drives the real report-draft
node (``node_12_draft_json``) end-to-end.  The check passes only when:

1. an HTTP POST actually arrived at ``/chat/completions`` (the call left the
   process — deterministic fallback never makes a network call);
2. the request carried a bearer Authorization header and the DeepSeek model id;
3. the report content returned by the node is the mock server's distinctive
   payload, not the deterministic fallback shell.

No real credentials are used or printed.  Run:

    LLM_PROVIDER=deepseek python scripts/validate_deepseek_provider.py
"""

from __future__ import annotations

import asyncio
import json
import os
import sys
import threading
from http.server import BaseHTTPRequestHandler, HTTPServer

MARKER = "DEEPSEEK-UAT-MARKER-2026-06-12"

# Configure the environment BEFORE importing app settings.
os.environ["LLM_PROVIDER"] = "deepseek"
os.environ["DEEPSEEK_API_KEY"] = "local-validation-not-a-real-key"

_requests_seen: list[dict] = []


class _MockDeepSeek(BaseHTTPRequestHandler):
    def do_POST(self) -> None:  # noqa: N802
        body = self.rfile.read(int(self.headers.get("Content-Length", 0)))
        payload = json.loads(body.decode("utf-8"))
        _requests_seen.append({
            "path": self.path,
            "authorization_header_present": bool(self.headers.get("Authorization")),
            "model": payload.get("model"),
            "max_tokens": payload.get("max_tokens"),
            "prompt_chars": len(payload["messages"][0]["content"]),
        })
        report = {
            "request_id": "uat-ds-001",
            "project_code": "PRJ-001",
            "query": "validation",
            "language": "en",
            "executive_summary": [f"Generated by mock DeepSeek endpoint: {MARKER}"],
            "financial_snapshot": {
                "budget": {"value": 1, "currency": "AED", "evidence_id": "ev-1", "status": "ok"},
                "actual_cost": {"value": 1, "currency": "AED", "evidence_id": "ev-1", "status": "ok"},
                "variance": {"value": 0, "currency": "AED", "formula": None, "evidence_ids": []},
            },
            "key_findings": [MARKER],
            "root_causes": [],
            "delay_analysis": [],
            "contractual_implications": [],
            "recommended_actions": [],
            "missing_data": [],
            "conflicts": [],
            "sources": [],
            "quality_gate_status": "not_run",
        }
        response = json.dumps({
            "model": "deepseek-chat",
            "choices": [{"message": {"role": "assistant", "content": json.dumps(report)}}],
            "usage": {"prompt_tokens": 321, "completion_tokens": 123},
        }).encode("utf-8")
        self.send_response(200)
        self.send_header("Content-Type", "application/json")
        self.send_header("Content-Length", str(len(response)))
        self.end_headers()
        self.wfile.write(response)

    def log_message(self, *args) -> None:  # silence default request logging
        pass


def main() -> int:
    server = HTTPServer(("127.0.0.1", 0), _MockDeepSeek)
    port = server.server_address[1]
    os.environ["DEEPSEEK_BASE_URL"] = f"http://127.0.0.1:{port}"
    threading.Thread(target=server.serve_forever, daemon=True).start()

    # Import AFTER the env is staged so Settings picks it up.
    from apps.edr.config import settings
    from apps.edr.graph import node_12_draft_json
    from apps.edr.graph.state import DecisionState
    from apps.edr.llm import active_provider

    checks: dict[str, bool] = {}
    checks["llm_provider_resolved_deepseek"] = active_provider() == "deepseek"
    checks["anthropic_key_not_required"] = not settings.anthropic_api_key

    state = DecisionState(
        request_id="uat-ds-001",
        user_id="uat-user",
        role="executive",
        project_code="PRJ-001",
        query="What is the budget vs actual cost for this project?",
        evidence=[{
            "evidence_id": "ev-1",
            "source_type": "odoo",
            "title": "Project budget record",
            "source_uri": "odoo://project.project/1",
            "snippet": "Budget AED 1; Actual AED 1.",
        }],
    )
    result_state = asyncio.run(node_12_draft_json.run(state))

    report = result_state.report_json or {}
    checks["http_request_reached_mock_endpoint"] = len(_requests_seen) == 1
    req = _requests_seen[0] if _requests_seen else {}
    checks["endpoint_is_chat_completions"] = req.get("path") == "/chat/completions"
    checks["authorization_header_present"] = req.get("authorization_header_present") is True
    checks["deepseek_model_requested"] = req.get("model") == "deepseek-chat"
    checks["report_content_from_deepseek_not_fallback"] = MARKER in json.dumps(report)
    checks["fallback_shell_absent"] = "fallback mode" not in json.dumps(report).lower()
    checks["usage_tokens_recorded"] = result_state.outputs.get("node_12_cost_usd", 0) > 0

    server.shutdown()

    print("DeepSeek provider runtime validation")
    print(f"  request observed: {json.dumps(req)}")
    for name, ok in checks.items():
        print(f"  [{'PASS' if ok else 'FAIL'}] {name}")
    overall = all(checks.values())
    print(f"RESULT: {'PASS' if overall else 'FAIL'}")
    return 0 if overall else 1


if __name__ == "__main__":
    sys.exit(main())
